import {test,expect} from '@playwright/test';

test('integrated intros reuse the squad, save settings and preserve existing modes',async({page})=>{
 test.setTimeout(90000);const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto('/');
 const photo=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=120;c.height=160;const x=c.getContext('2d')!;x.fillStyle='#e430aa';x.fillRect(30,20,60,120);return c.toDataURL().split(',')[1];});
 await page.getByLabel('Player photo',{exact:true}).setInputFiles({name:'player.png',mimeType:'image/png',buffer:Buffer.from(photo,'base64')});
 await page.getByRole('button',{name:'Keep Original',exact:true}).click();
 await page.getByRole('button',{name:'Apply',exact:true}).click();
 await page.getByRole('button',{name:'TEAM INTRO',exact:true}).click();
 const team=page.frameLocator('iframe[title="Team Intro Studio"]');
 await expect(team.locator('#team-name')).toHaveValue('NONDAENG FC');
 await expect(team.locator('[data-name="0"]')).toHaveValue('KITTIPONG');
 await expect(team.locator('[data-name="10"]')).toHaveValue('TEERAPAT');
 await expect(team.locator('[data-player="8"] img')).toBeVisible();
 await team.locator('#team-name').fill('MERGED TEAM');
 await team.locator('#team-formation').selectOption('5-4-1');
 await team.locator('[data-chapter="5"]').click();
 await expect.poll(async()=>page.getByRole('button',{name:'Save',exact:true}).isEnabled()).toBe(true);
 await page.waitForTimeout(700);
 await page.getByRole('button',{name:'Save',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('saved');
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('touchline.projects.v1')||'[]')[0]);
 expect(JSON.parse(saved.introStudio.team).inputs['team-name']).toBe('MERGED TEAM');
 await page.getByRole('button',{name:'LINEUP',exact:true}).click();await expect(page.getByRole('button',{name:'Select KITTIPONG',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'TEAM INTRO',exact:true}).click();await expect(team.locator('#team-name')).toHaveValue('MERGED TEAM');
 await expect(team.locator('#team-formation')).toHaveValue('5-4-1');
 const imageDownload=page.waitForEvent('download');await team.locator('#team-snapshot').click();expect((await imageDownload).suggestedFilename()).toMatch(/\.png$/);
 await page.getByRole('button',{name:'PLAYER INTRO',exact:true}).click();
 const player=page.frameLocator('iframe[title="Player Intro Studio"]');
 await expect(player.locator('#team')).toHaveValue('NONDAENG FC');
 await page.getByLabel('เลือกนักเตะสำหรับคลิป').selectOption({label:'1 · KITTIPONG'});
 await page.getByRole('button',{name:'ใช้ข้อมูลนักเตะที่เลือก'}).click();
 await expect(player.locator('#player-name')).toHaveValue('KITTIPONG');
 await player.locator('#duration').selectOption('6');
 const videoDownload=page.waitForEvent('download');await player.locator('#export').click();expect((await videoDownload).suggestedFilename()).toMatch(/\.(mp4|webm)$/);
 await page.waitForTimeout(700);
 await page.getByRole('button',{name:'MATCH RESULT',exact:true}).click();
 await expect(page.getByRole('button',{name:'MATCH RESULT',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.getByRole('button',{name:'Load',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:'Load',exact:true}).click();
 await page.getByRole('button',{name:'TEAM INTRO',exact:true}).click();
 await expect(team.locator('#team-name')).toHaveValue('MERGED TEAM');
 await expect(team.locator('[data-player="8"] img')).toBeVisible();
 await page.screenshot({path:'test-results/integrated-intro.png',fullPage:true});
 expect(errors).toEqual([]);
});
