'use client';
import { useEffect, useRef, useState } from 'react';
import { Copy, Download, FolderOpen, Trash2, Upload, X } from 'lucide-react';
import type { Project } from '@/types/project';
import { projectRepository } from '@/services/project-storage';
import { validateProject } from '@/lib/validation';
import { backupProject } from '@/lib/export';
export function ProjectLibrary({ current, onLoad, onClose, onDelete, notify }: { current: Project; onLoad: (project: Project, saved: boolean) => void; onClose: () => void; onDelete: (id: string) => void; notify: (message: string) => void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [projects, setProjects] = useState<Project[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { dialog.current?.showModal(); let active = true; void Promise.resolve().then(() => projectRepository().list()).then((items) => { if (active) setProjects(items); }).catch((e: Error) => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const action = async (work: () => Promise<void>) => { setBusy(true); setError(''); try { await work(); } catch (e) { setError(e instanceof Error ? e.message : 'Project action failed.'); } finally { setBusy(false); } };
  return <dialog ref={dialog} className="library-dialog" onCancel={onClose} onClick={(event) => { if (event.target === event.currentTarget) onClose(); }} aria-labelledby="library-title"><div className="library-inner"><div className="library-header"><div><span className="eyebrow">YOUR MATCHDAYS</span><h2 id="library-title">Project library</h2></div><button className="icon-button" aria-label="Close project library" onClick={onClose}><X size={19} /></button></div><p className="muted">Projects are saved in this browser. Keep a JSON backup to move between devices or preserve image-heavy squads.</p><div className="library-tools"><button className="button" disabled={busy} onClick={() => void action(async () => { const copy = await projectRepository().duplicate(current); onLoad(copy, true); notify('Project duplicated and saved.'); onClose(); })}><Copy size={14} />Duplicate current</button><button className="button" onClick={() => backupProject(current)}><Download size={14} />JSON backup</button><label className="button import-label"><Upload size={14} />Import JSON<input aria-label="Import project JSON" type="file" accept="application/json,.json" disabled={busy} onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; void action(async () => { if (file.size > 80 * 1024 * 1024) throw new Error('Project backup must be under 80 MB.'); const loaded = validateProject(JSON.parse(await file.text())); onLoad({ ...loaded, id: crypto.randomUUID() }, false); notify('Backup imported. Save to keep it in this browser.'); onClose(); }); }} /></label></div>{error && <p className="library-error" role="alert">{error}</p>}<div className="library-projects">{loading ? <p className="muted">Loading projects…</p> : projects.length ? projects.map((p) => <div className="library-project" key={p.id}><span className="library-swatch" style={{ background: p.colors.secondary }}><FolderOpen size={21} /></span><div><strong>{p.name || 'Untitled project'}</strong><small>{p.team.name} · {p.formation} · {new Date(p.updatedAt).toLocaleDateString()}</small></div><button className="button" disabled={busy} onClick={() => { onLoad(p, true); notify('Project loaded.'); onClose(); }}>Load</button><button className="icon-button" aria-label={`Delete project ${p.name}`} disabled={busy} onClick={() => { if (confirm(`Delete saved project “${p.name}”? This cannot be undone.`)) void action(async () => { await projectRepository().remove(p.id); onDelete(p.id); setProjects(await projectRepository().list()); notify('Saved project deleted.'); }); }}><Trash2 size={16} /></button></div>) : <div className="library-empty"><FolderOpen size={30} /><strong>No saved matchdays yet</strong><p>Close this window and choose Save to keep your current lineup.</p></div>}</div></div></dialog>;
}


