import type { Player, Project, StartingLineup } from '@/types/project';
import { SIZES } from '@/types/project';
import { drawBackground } from './background-renderer';
import { drawContained, loadImage } from '@/utils/images';

function fitText(ctx: CanvasRenderingContext2D, value: string, x: number, y: number, size: number, max: number, color: string, align: CanvasTextAlign = 'left', weight = 700) { ctx.fillStyle = color; ctx.textAlign = align; ctx.textBaseline = 'middle'; ctx.font = `${weight} ${size}px Arial, "Noto Sans Thai", Tahoma, sans-serif`; ctx.fillText(value, x, y, max); }
function nameFor(player: Player, data: StartingLineup, entry: { playerId: string; displayName?: string }) { if (entry.displayName) return entry.displayName; if (data.nameStyle === 'nickname' && player.nickname) return player.nickname; if (data.nameStyle === 'surname') { const words = player.name.trim().split(/\s+/); return words.length > 1 ? `${words.slice(0, -1).join(' ')} ${words.at(-1)!.toUpperCase()}` : player.name; } return player.name; }
export async function renderStartingLineup(canvas: HTMLCanvasElement, project: Project) {
  const data = project.startingLineup; if (!data) throw new Error('Starting lineup data is missing.');
  const players = new Map(project.players.map((p) => [p.id, p])); const hero = data.hero.src || (data.hero.playerId ? players.get(data.hero.playerId)?.photo : '') || '';
  const sources = [...new Set([hero, project.team.logo, data.competitionLogo, data.matchInfo.opponentLogo, ...data.sponsors.map((s) => s.src), data.background.kind === 'custom' ? data.background.image : ''].filter(Boolean))];
  const images = new Map(await Promise.all(sources.map(async (src) => [src, await loadImage(src)] as const))); const [w, h] = SIZES[data.size]; canvas.width = w; canvas.height = h; const ctx = canvas.getContext('2d'); if (!ctx) throw new Error('Canvas is unavailable.');
  drawBackground(ctx, { ...project, colors: data.colors, background: data.background, template: project.template }, w, h, images.get(data.background.image)); const u = Math.min(w, h) / 1080; const ink = data.colors.text; const light = data.template === 'minimal-lineup';
  const panelX = w * .46; const panelW = w * .49; const top = h * .08; const bottom = h * (data.matchInfo.enabled ? .88 : .94); const listTop = top + h * .2; const listBottom = bottom - h * .12; const rowH = Math.max(34 * u, (listBottom - listTop) / 11);
  ctx.fillStyle = light ? '#ffffffdf' : '#030713db'; ctx.fillRect(panelX, 0, panelW, h); ctx.fillStyle = data.colors.accent; ctx.fillRect(panelX, 0, w * .014, h);
  const logo = images.get(project.team.logo); if (logo) drawContained(ctx, logo, panelX + w * .035, top, 72 * u, 72 * u);
  fitText(ctx, data.title, panelX + w * .14, top + 23 * u, 30 * u, panelW * .75, ink, 'left', 900); fitText(ctx, project.team.name, panelX + w * .14, top + 59 * u, 18 * u, panelW * .76, ink, 'left', 700); fitText(ctx, project.team.competition, panelX + w * .14, top + 82 * u, 12 * u, panelW * .76, ink, 'left', 500); const competitionLogo = images.get(data.competitionLogo); if (competitionLogo) drawContained(ctx, competitionLogo, panelX + panelW - w * .12, top + 6 * u, 54 * u, 54 * u);
  ctx.fillStyle = data.colors.accent; ctx.fillRect(panelX + w * .035, listTop - 28 * u, panelW - w * .07, 3 * u); fitText(ctx, 'STARTING XI', panelX + w * .035, listTop - 8 * u, 14 * u, panelW - w * .07, ink, 'left', 800);
  data.starters.slice(0, 11).forEach((entry, index) => { const p = players.get(entry.playerId); if (!p) return; const y = listTop + index * rowH + rowH / 2; ctx.fillStyle = index % 2 ? `${data.colors.secondary}55` : `${data.colors.primary}25`; ctx.fillRect(panelX + w * .025, y - rowH / 2, panelW - w * .05, rowH - 2 * u); fitText(ctx, p.number, panelX + w * .07, y, 19 * u, 42 * u, data.colors.accent, 'center', 900); fitText(ctx, nameFor(p, data, entry).toUpperCase(), panelX + w * .12, y, 17 * u, panelW * .65, ink, 'left', 800); fitText(ctx, p.position, panelX + panelW - w * .08, y, 10 * u, 48 * u, `${ink}aa`, 'right', 500); if (entry.captain) { ctx.fillStyle = data.colors.accent; ctx.beginPath(); ctx.arc(panelX + panelW - w * .05, y, 11 * u, 0, Math.PI * 2); ctx.fill(); fitText(ctx, 'C', panelX + panelW - w * .05, y, 10 * u, 20 * u, '#ffffff', 'center', 900); } });
  const subY = bottom - 35 * u; fitText(ctx, 'SUBSTITUTES', panelX + w * .035, subY, 12 * u, panelW - w * .07, ink, 'left', 800); const subNames = data.substitutes.map((id) => players.get(id)).filter(Boolean).map((p) => `${p!.number} ${nameFor(p!, data, { playerId: p!.id })}`).join(data.substituteLayout === 'compact' ? '  ·  ' : '   '); fitText(ctx, subNames, panelX + w * .035, subY + 22 * u, 11 * u, panelW - w * .07, ink, 'left', 500);
  if (data.matchInfo.enabled) { ctx.fillStyle = `${data.colors.accent}cc`; ctx.fillRect(panelX + w * .035, bottom + 15 * u, panelW - w * .07, 2 * u); const opponent = images.get(data.matchInfo.opponentLogo); if (opponent) drawContained(ctx, opponent, panelX + w * .035, bottom + 29 * u, 35 * u, 35 * u); fitText(ctx, `${data.matchInfo.opponent}  •  ${data.matchInfo.date}  ${data.matchInfo.time}`, panelX + w * .09, bottom + 47 * u, 11 * u, panelW - w * .15, ink, 'left', 600); fitText(ctx, [data.matchInfo.round, data.matchInfo.venue].filter(Boolean).join('  •  '), panelX + w * .09, bottom + 65 * u, 10 * u, panelW - w * .15, `${ink}aa`, 'left', 500); }
  if (data.showSponsors && data.sponsors.length) { const y = data.sponsorPosition === 'top' ? h * .04 : h * .95; data.sponsors.slice(0, 6).forEach((s, i) => { const img = images.get(s.src); if (img) drawContained(ctx, img, panelX + panelW - w * .18 - i * w * .07, y, 50 * u, 28 * u); }); }
  const heroImage = images.get(hero); if (heroImage) { const heroW = w * .53; const heroH = h * .8; const scale = Math.max(heroW / heroImage.naturalWidth, heroH / heroImage.naturalHeight) * data.hero.zoom; const iw = heroImage.naturalWidth * scale; const ih = heroImage.naturalHeight * scale; ctx.save(); ctx.globalAlpha = 1; ctx.drawImage(heroImage, w * .03 + (heroW - iw) / 2 + data.hero.x * w * .01, h * .17 + (heroH - ih) / 2 + data.hero.y * h * .01, iw, ih); ctx.restore(); }
}
